stages:
  01_load_data:
    cmd: python src/01_load_and_save.py --config=params.yaml
    deps: 
      - src/01_load_and_save.py
    params:
      - s3_data_source.bucket_name
      - s3_data_source.bucket_folder_name
      - s3_data_source.s3_root_folder_prefix
      - s3_data_source.s3_folder_list
      - s3_data_source.region_name
    outs:
      - artifacts/waffer_batch_files

  02_validation:
    cmd: python src/02_validation.py --config=params.yaml --schema=schema.yaml
    deps: 
      - src/02_validation.py
      - artifacts/waffer_batch_files
    params:
      - schema.yaml:
        - LengthOfDateStampInFile
        - LengthOfTimeStampInFile
        - NumberofColumns
      - artifacts.02_validation.s3_data_dir
      - artifacts.02_validation.good_files_dir
      - artifacts.02_validation.bad_files_dir
    outs:
      - artifacts/02_validation/bad_files
      - artifacts/02_validation/good_files

  03_preprocess:
    cmd: python src/03_preprocess.py --config=params.yaml
    deps: 
      - src/03_preprocess.py
      - artifacts/02_validation/good_files
    params:
      - artifacts.03_preprocess.preprocess_dir
      - artifacts.03_preprocess.null_cols_fname
      - artifacts.03_preprocess.preprocessed_files
      - hyperparams.KNNImputer.n_neighbors
      - hyperparams.KNNImputer.weights
    outs:
      - artifacts/03_preprocess/preprocessed_files

  04_split_data:
    cmd: python src/04_split_data.py --config=params.yaml
    deps: 
      - src/04_split_data.py
      - artifacts/03_preprocess/preprocessed_files
    params:
      - base.random_state
      - base.test_size
      - artifacts.04_split_data.split_data_dir
    outs:
      - artifacts/04_split_data/X_train.csv
      - artifacts/04_split_data/X_test.csv
      - artifacts/04_split_data/Y_train.csv
      - artifacts/04_split_data/Y_test.csv
      
  05_train:
    cmd: python src/05_train.py --config=params.yaml
    deps: 
      - src/05_train.py
      - artifacts/04_split_data/X_train.csv
      - artifacts/04_split_data/Y_train.csv
    params:
      - base.random_state
      - hyperparams.balanced_random_forest
      - hyperparams.balanced_bagging_classifer
      - hyperparams.easy_ensemble_classifier
    outs:
      - artifacts/05_train


  06_evaluate:
    cmd: python src/06_evaluate.py --config=params.yaml
    deps:
      - src/06_evaluate.py
      - artifacts/05_train
    params:
      - artifacts.06_evaluate.evaluate_on
    outs:
      - artifacts/06_evaluate/results
      - artifacts/06_evaluate/best_model